telegram.ext.dispatcher-ERROR-An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/telegram/ext/messagehandler.py", line 169, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 21, in talk_to_me
    user_text=update.message.user_text
AttributeError: 'Message' object has no attribute 'user_text'
telegram.ext.updater-WARNING-Exiting immediately!
